### ISSUE TITLE
IDE Copy Feature

### ISSUE THREAD

**Issue by Daxz0** [Hydroxycobalamin/Denizen-Script-Collection#13]
### I confirm that...

- [X] I checked the issues page for similar issues. This Feature request won't be a duplicate.
- [X] I made sure that this feature does not exist yet by asking on the Discord or reading the Wiki.

### Script

Item Display Editor

### Description

Copies displays or groups. Simple proof of concept, could be polished for sure.
```yml
IDE_copy_selection:
    type: task
    debug: false
    script:
        - ratelimit <player> 1t
        - if <player.has_flag[item_display_editor.selected_displays]>:
            - foreach <player.flag[item_display_editor.selected_displays]> as:d:
                - spawn <[d].describe> <[d].location>
                - narrate "<&[base]>Copied group dispaly!"
        - else if <player.has_flag[item_display_editor.selected_display]>:
            - spawn <player.flag[item_display_editor.selected_display].describe> <player.flag[item_display_editor.selected_display].location>
            - narrate "<&[base]>Copied display!"
 ```
